<?php

namespace App\Services\Accounting;

use App\Models\Accounting\DeliveryNote;
use App\Models\Accounting\DocumentAttachment;
use App\Models\Accounting\Invoice;
use App\Models\Accounting\Quotation;
use App\Models\Accounting\Receipt;
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;

/**
 * PDF Cache Service.
 *
 * Manages PDF caching with an organized directory structure under
 * `storage/app/public/pdfs-cache/{document_type}/{year}/{month}/`.
 *
 * The cache uses `DocumentAttachment` rows with `attachment_type = 'cached_pdf'`
 * to bridge filesystem files with TTL/version metadata. Lookups happen by a
 * deterministic `cache_key` (see `generateCacheKey()`) and bust automatically
 * when the underlying document's relevant fields change (`calculateCacheVersion()`).
 */
class PdfCacheService
{
    /**
     * TTL configurations based on document status (in minutes).
     */
    public const TTL_DRAFT = 30;          // 30 minutes

    public const TTL_APPROVED = 1440;     // 24 hours

    public const TTL_SENT = 10080;        // 7 days

    public const TTL_COMPLETED = 10080;   // 7 days

    /**
     * DocumentAttachment.attachment_type discriminator for cached PDF rows.
     */
    private const ATTACHMENT_TYPE_CACHE = 'cached_pdf';

    /**
     * Filesystem prefix (relative to storage/app/public/) for cached PDFs.
     */
    private const CACHE_BASE_DIR = 'pdfs-cache';

    /**
     * Hours to keep soft-deleted cache entries before physical removal.
     */
    private const SOFT_DELETE_GRACE_HOURS = 24;

    /**
     * MIME type stamped onto every cached PDF row. Centralised so future format
     * changes (e.g. PDF/A) only touch one place.
     */
    private const MIME_PDF = 'application/pdf';

    /**
     * Variants generated by Invoice-class PDFs. The Invoice model is shared by
     * tax invoice / receipt / *_full services that override
     * `getFilenamePrefix()` to set the cache document_type — when an Invoice
     * row changes we must invalidate all of these in one shot, otherwise
     * derived cached PDFs continue to serve stale totals.
     */
    private const INVOICE_VARIANTS = [
        'invoice',
        'tax_invoice',
        'tax_invoice_full',
        'receipt',
        'receipt_full',
    ];

    /**
     * Per-request memoization of the version hash. Keyed by
     * "{class}:{id}:{updated_at}" so a single request never recomputes the
     * hash multiple times (generatePdf flow currently asks for it 3x).
     *
     * @var array<string, string>
     */
    private array $versionCache = [];

    // ---------------------------------------------------------------------
    // Public API
    // ---------------------------------------------------------------------

    /**
     * Get a cached PDF if a fresh, valid entry exists for this document +
     * options combination. Returns null on miss / expiry / missing file.
     *
     * @param  string  $documentType  ('quotation' | 'invoice' | 'receipt' | 'delivery_note')
     * @param  array<string, mixed>  $options
     * @return array<string, mixed>|null
     */
    public function getCached(string $documentType, string $documentId, array $options = []): ?array
    {
        try {
            $document = $this->getDocument($documentType, $documentId);
            if (! $document) {
                return null;
            }

            $cacheKey = $this->generateCacheKey($documentType, $documentId, $options, $document);

            $cacheEntry = DocumentAttachment::where('cache_key', $cacheKey)
                ->where('attachment_type', self::ATTACHMENT_TYPE_CACHE)
                ->whereNull('deleted_at')
                ->where(function ($query) {
                    $query->whereNull('cache_expires_at')
                        ->orWhere('cache_expires_at', '>', Carbon::now());
                })
                ->first();

            if (! $cacheEntry) {
                Log::info('PDF Cache MISS', ['cache_key' => $cacheKey]);

                return null;
            }

            $fullPath = storage_path('app/public/'.$cacheEntry->file_path);
            if (! file_exists($fullPath)) {
                Log::warning('PDF Cache entry exists but file missing', [
                    'cache_key' => $cacheKey,
                    'path' => $fullPath,
                ]);
                $cacheEntry->delete();

                return null;
            }

            Log::info('PDF Cache HIT', [
                'cache_key' => $cacheKey,
                'expires_at' => $cacheEntry->cache_expires_at,
            ]);

            return [
                'path' => $fullPath,
                'url' => asset('storage/'.$cacheEntry->file_path),
                'filename' => $cacheEntry->filename,
                'size' => $cacheEntry->file_size,
                'cached_at' => $cacheEntry->created_at,
                'expires_at' => $cacheEntry->cache_expires_at,
                'cache_version' => $cacheEntry->cache_version,
                'from_cache' => true,
            ];

        } catch (\Exception $e) {
            Log::error('PDF Cache getCached error: '.$e->getMessage(), [
                'document_type' => $documentType,
                'document_id' => $documentId,
            ]);

            return null;
        }
    }

    /**
     * Store a freshly-generated PDF in the cache. The PDF is copied to the
     * organized directory structure and a DocumentAttachment row records the
     * key/version/TTL metadata.
     *
     * Any existing live cache entries with the same `cache_key` are
     * soft-deleted before the insert so that `force_regenerate` paths and
     * concurrent stampede MISSes don't leave non-deterministic duplicates.
     *
     * @param  object  $document  Document model instance (Quotation/Invoice/Receipt/DeliveryNote)
     * @param  string  $pdfPath  Absolute path to the generated PDF
     * @param  array<string, mixed>  $options  Generation options (document_header_type, deposit_mode, ...)
     * @param  string|null  $documentType  Explicit cache document_type. When null,
     *                                     falls back to class-name guessing. Master
     *                                     services should always pass this so derived
     *                                     PDFs (tax_invoice, receipt_full, ...) land
     *                                     in their own cache buckets.
     * @return array<string, mixed>
     */
    public function store($document, string $pdfPath, array $options = [], ?string $documentType = null): array
    {
        $documentType = $documentType ?? $this->getDocumentType($document);
        $documentId = $document->id;

        try {
            $cacheVersion = $this->calculateCacheVersion($document);
            $cacheKey = $this->generateCacheKey($documentType, $documentId, $options, $document);
            $ttlMinutes = $this->calculateTTL($document);
            $expiresAt = $ttlMinutes > 0 ? Carbon::now()->addMinutes($ttlMinutes) : null;

            $storagePath = $this->getStoragePath($documentType, Carbon::now());
            $storageFullPath = $this->prepareStorageDirectory($storagePath);

            $filename = $this->buildCacheFilename(
                $documentType,
                $documentId,
                $document->number ?? null,
                $options['document_header_type'] ?? 'default'
            );

            $destinationPath = $storageFullPath.DIRECTORY_SEPARATOR.$filename;
            if (! @copy($pdfPath, $destinationPath)) {
                $err = error_get_last();
                throw new \Exception(sprintf(
                    'Failed to copy PDF to cache location: %s → %s (%s)',
                    $pdfPath,
                    $destinationPath,
                    $err['message'] ?? 'unknown'
                ));
            }

            $fileSize = filesize($destinationPath);

            // Soft-delete any existing live rows that share this cache_key so
            // that subsequent `getCached()` lookups deterministically pick the
            // freshest entry. cleanupExpired() handles the physical files
            // after the grace period.
            DocumentAttachment::where('cache_key', $cacheKey)
                ->where('attachment_type', self::ATTACHMENT_TYPE_CACHE)
                ->whereNull('deleted_at')
                ->update(['deleted_at' => Carbon::now()]);

            $cacheEntry = DocumentAttachment::create([
                'document_type' => $documentType,
                'document_id' => $documentId,
                'attachment_type' => self::ATTACHMENT_TYPE_CACHE,
                'filename' => $filename,
                'original_filename' => $filename,
                'file_path' => $storagePath.$filename,
                'file_size' => $fileSize,
                'mime_type' => self::MIME_PDF,
                'cache_expires_at' => $expiresAt,
                'cache_version' => $cacheVersion,
                'cache_key' => $cacheKey,
                'uploaded_by' => $this->resolveActorId($options, $document),
            ]);

            Log::info('PDF Cache STORED', [
                'cache_key' => $cacheKey,
                'path' => $storagePath.$filename,
                'ttl_minutes' => $ttlMinutes,
                'expires_at' => $expiresAt,
            ]);

            return [
                'cache_entry_id' => $cacheEntry->id,
                'path' => $destinationPath,
                'url' => asset('storage/'.$storagePath.$filename),
                'filename' => $filename,
                'size' => $fileSize,
                'expires_at' => $expiresAt,
                'ttl_minutes' => $ttlMinutes,
            ];

        } catch (\Exception $e) {
            Log::error('PDF Cache store error: '.$e->getMessage(), [
                'document_type' => $documentType,
                'document_id' => $documentId,
            ]);
            throw $e;
        }
    }

    /**
     * Soft-delete cache entries for a document. Accepts either a single
     * document_type string or an array — the array form is required for
     * Invoice-class invalidation where the row update needs to cascade into
     * tax_invoice / receipt / *_full caches (each living under its own type).
     *
     * @param  string|array<int, string>  $documentType
     */
    public function invalidate($documentType, string $documentId): int
    {
        try {
            $types = is_array($documentType) ? array_values($documentType) : [$documentType];

            $count = DocumentAttachment::whereIn('document_type', $types)
                ->where('document_id', $documentId)
                ->where('attachment_type', self::ATTACHMENT_TYPE_CACHE)
                ->whereNull('deleted_at')
                ->update(['deleted_at' => Carbon::now()]);

            Log::info('PDF Cache INVALIDATED', [
                'document_types' => $types,
                'document_id' => $documentId,
                'count' => $count,
            ]);

            return (int) $count;

        } catch (\Exception $e) {
            Log::error('PDF Cache invalidate error: '.$e->getMessage());

            return 0;
        }
    }

    /**
     * Convenience wrapper that resolves the full set of cache document_types
     * for a model instance and invalidates all of them at once. Use this from
     * model `updated`/`deleted` boot hooks instead of calling `invalidate()`
     * with a hard-coded single type — Invoice rows in particular fan out to
     * five separate cache buckets.
     */
    public function invalidateAllForDocument($document): int
    {
        $primaryType = $this->getDocumentType($document);
        $types = $primaryType === 'invoice'
            ? self::INVOICE_VARIANTS
            : [$primaryType];

        return $this->invalidate($types, (string) $document->id);
    }

    /**
     * Build the deterministic cache key from document identity + options +
     * a content-version hash. Same inputs always yield the same key.
     *
     * @param  array<string, mixed>  $options
     */
    public function generateCacheKey(string $documentType, string $documentId, array $options, $document): string
    {
        $headerType = $options['document_header_type'] ?? 'default';
        $depositMode = $options['deposit_mode'] ?? 'default';
        $cacheVersion = $this->calculateCacheVersion($document);

        return sprintf(
            '%s:%s:%s:%s:%s',
            $documentType,
            $documentId,
            $headerType,
            $depositMode,
            $cacheVersion
        );
    }

    /**
     * Hash the fields that should bust the cache when they change. Loads the
     * customer + items relations on demand and memoizes the result per
     * request — the generate flow asks for the version up to three times
     * during a single `generatePdf` call, so without memoization we'd hash
     * the same data repeatedly and (worse) re-query items every time.
     *
     * @return string MD5 hex digest
     */
    public function calculateCacheVersion($document): string
    {
        $memoKey = sprintf(
            '%s:%s:%s',
            get_class($document),
            $document->id ?? '-',
            $document->updated_at?->timestamp ?? '-'
        );
        if (isset($this->versionCache[$memoKey])) {
            return $this->versionCache[$memoKey];
        }

        if (! $document->relationLoaded('customer') && method_exists($document, 'customer')) {
            $document->load('customer');
        }
        // Items are part of the version signature unconditionally — relying on
        // the parent's `updated_at` alone misses cases where items are touched
        // via a relation method that doesn't cascade the parent timestamp.
        if (method_exists($document, 'items') && ! $document->relationLoaded('items')) {
            $document->load('items');
        }

        $data = [
            'updated_at' => $document->updated_at ? $document->updated_at->timestamp : time(),
            'customer_id' => $document->customer_id ?? null,
            'customer_updated_at' => $document->customer?->cus_updated_date?->timestamp ?? null,
            'status' => $document->status ?? null,
            'total_amount' => $document->total_amount ?? null,
        ];

        if (method_exists($document, 'items') && $document->relationLoaded('items')) {
            $data['items'] = $document->items->map(fn ($item) => [
                'id' => $item->id,
                'quantity' => $item->quantity ?? null,
                'unit_price' => $item->unit_price ?? null,
                'updated_at' => $item->updated_at?->timestamp ?? null,
            ])->toArray();
        }

        return $this->versionCache[$memoKey] = md5(serialize($data));
    }

    /**
     * Sweep expired cache entries: removes physical files, hard-deletes their
     * DocumentAttachment rows, then prunes empty directories.
     *
     * @param  int  $softDeleteGracePeriodHours  Hours to keep soft-deleted entries before physical deletion
     * @return array{deleted_count: int, freed_space: int}
     */
    public function cleanupExpired(int $softDeleteGracePeriodHours = self::SOFT_DELETE_GRACE_HOURS): array
    {
        try {
            $deletedCount = 0;
            $freedSpace = 0;

            // Chunk to avoid loading the entire expired-row set into memory
            // when the cache table accumulates thousands of entries.
            DocumentAttachment::where('attachment_type', self::ATTACHMENT_TYPE_CACHE)
                ->where(function ($query) use ($softDeleteGracePeriodHours) {
                    $query->where('cache_expires_at', '<=', Carbon::now())
                        ->orWhere('deleted_at', '<=', Carbon::now()->subHours($softDeleteGracePeriodHours));
                })
                ->orderBy('id')
                ->chunk(500, function ($entries) use (&$deletedCount, &$freedSpace) {
                    foreach ($entries as $entry) {
                        $fullPath = storage_path('app/public/'.$entry->file_path);

                        if (file_exists($fullPath)) {
                            $freedSpace += (int) @filesize($fullPath);
                            @unlink($fullPath);
                        }

                        $entry->forceDelete();
                        $deletedCount++;
                    }
                });

            $this->cleanupEmptyDirectories();

            Log::info('PDF Cache CLEANUP completed', [
                'deleted_count' => $deletedCount,
                'freed_space_mb' => round($freedSpace / 1024 / 1024, 2),
            ]);

            return [
                'deleted_count' => $deletedCount,
                'freed_space' => $freedSpace,
            ];

        } catch (\Exception $e) {
            Log::error('PDF Cache cleanup error: '.$e->getMessage());

            return ['deleted_count' => 0, 'freed_space' => 0];
        }
    }

    /**
     * Aggregate metrics for the cache (counts, total size, expired count,
     * breakdown by document type).
     *
     * @return array<string, mixed>
     */
    public function getStatistics(): array
    {
        $base = fn () => DocumentAttachment::where('attachment_type', self::ATTACHMENT_TYPE_CACHE)->whereNull('deleted_at');

        $totalEntries = $base()->count();
        $totalSize = (int) $base()->sum('file_size');

        $expiredCount = $base()
            ->where('cache_expires_at', '<=', Carbon::now())
            ->count();

        $byDocumentType = $base()
            ->selectRaw('document_type, COUNT(*) as count, SUM(file_size) as size')
            ->groupBy('document_type')
            ->get();

        return [
            'total_entries' => $totalEntries,
            'total_size_bytes' => $totalSize,
            'total_size_mb' => round($totalSize / 1024 / 1024, 2),
            'expired_count' => $expiredCount,
            'by_document_type' => $byDocumentType->toArray(),
        ];
    }

    // ---------------------------------------------------------------------
    // Private helpers — TTL, paths, filenames
    // ---------------------------------------------------------------------

    /**
     * Map document status → TTL (minutes). Unknown status falls back to draft TTL.
     */
    protected function calculateTTL($document): int
    {
        $status = strtolower($document->status ?? 'draft');

        if (in_array($status, ['draft', 'pending'], true)) {
            return self::TTL_DRAFT;
        }

        if (in_array($status, ['approved'], true)) {
            return self::TTL_APPROVED;
        }

        if (in_array($status, ['sent', 'completed', 'delivered'], true)) {
            return self::TTL_SENT;
        }

        return self::TTL_DRAFT;
    }

    /**
     * Relative cache path under storage/app/public/ — e.g.
     * `pdfs-cache/invoice/2026/05/`.
     */
    protected function getStoragePath(string $documentType, Carbon $date): string
    {
        return sprintf(
            '%s/%s/%s/%s/',
            self::CACHE_BASE_DIR,
            $documentType,
            $date->format('Y'),
            $date->format('m')
        );
    }

    /**
     * Ensure the absolute storage directory exists, creating it (recursive)
     * when missing. Returns the absolute path.
     *
     * `@mkdir() || is_dir()` is the canonical race-safe pattern — under
     * concurrent stores, one process wins the actual mkdir and the others
     * see is_dir()=true on retry without throwing a notice.
     */
    private function prepareStorageDirectory(string $relativeStoragePath): string
    {
        $storageFullPath = storage_path('app/public/'.$relativeStoragePath);

        if (! is_dir($storageFullPath) && ! @mkdir($storageFullPath, 0755, true) && ! is_dir($storageFullPath)) {
            throw new \RuntimeException("Failed to create PDF cache directory: {$storageFullPath}");
        }

        return $storageFullPath;
    }

    /**
     * Build the cached PDF filename:
     *   <documentType>-<documentNumberOrId>-<sanitizedHeader>-<timestamp>.pdf
     */
    private function buildCacheFilename(
        string $documentType,
        string $documentId,
        ?string $documentNumber,
        string $headerType
    ): string {
        return sprintf(
            '%s-%s-%s-%s.pdf',
            $documentType,
            $documentNumber ?: $documentId,
            $this->sanitizeFilename($headerType),
            Carbon::now()->format('YmdHis')
        );
    }

    /**
     * Resolve the actor id for the cache entry. Tries auth context first,
     * falls back to options['user_id'], then the document's created_by.
     *
     * @param  array<string, mixed>  $options
     */
    private function resolveActorId(array $options, $document): ?string
    {
        if (auth()->check()) {
            return auth()->user()->user_uuid ?? auth()->id();
        }

        if (! empty($options['user_id'])) {
            return $options['user_id'];
        }

        if (! empty($document->created_by)) {
            return $document->created_by;
        }

        return null;
    }

    // ---------------------------------------------------------------------
    // Private helpers — cleanup
    // ---------------------------------------------------------------------

    protected function cleanupEmptyDirectories(): void
    {
        $basePath = storage_path('app/public/'.self::CACHE_BASE_DIR);
        if (! is_dir($basePath)) {
            return;
        }

        $this->removeEmptySubfolders($basePath);
    }

    /**
     * Recursively remove empty subdirectories. Never removes the root cache
     * directory itself.
     */
    protected function removeEmptySubfolders(string $path): void
    {
        $empty = true;
        foreach (glob($path.DIRECTORY_SEPARATOR.'*') as $file) {
            if (is_dir($file)) {
                $this->removeEmptySubfolders($file);
                if (is_dir($file)) {
                    $empty = false;
                }
            } else {
                $empty = false;
            }
        }

        if ($empty && $path !== storage_path('app/public/'.self::CACHE_BASE_DIR)) {
            @rmdir($path);
        }
    }

    // ---------------------------------------------------------------------
    // Private helpers — document type resolution
    // ---------------------------------------------------------------------

    /**
     * Resolve a model instance for `getCached()` to compute the cache version.
     * Returns null when the document type is unknown or the row is missing.
     */
    protected function getDocument(string $documentType, string $documentId): ?object
    {
        $modelMap = [
            'quotation' => Quotation::class,
            'invoice' => Invoice::class,
            'receipt' => Receipt::class,
            'delivery_note' => DeliveryNote::class,
        ];

        $modelClass = $modelMap[$documentType] ?? null;
        if (! $modelClass) {
            return null;
        }

        return $modelClass::with('items')->find($documentId);
    }

    /**
     * Reverse-map a model instance to its primary `documentType` string.
     * Caller is responsible for fanning out to derived types when needed
     * (see `invalidateAllForDocument()`).
     */
    protected function getDocumentType($document): string
    {
        return match (true) {
            $document instanceof DeliveryNote => 'delivery_note',
            $document instanceof Quotation => 'quotation',
            $document instanceof Receipt => 'receipt',
            $document instanceof Invoice => 'invoice',
            default => 'unknown',
        };
    }

    /**
     * Sanitize a string for filesystem-safe use in filenames. Replaces
     * non-ASCII / special characters with `-` and caps length at 50 chars.
     */
    protected function sanitizeFilename(string $filename): string
    {
        $filename = preg_replace('/[^a-zA-Z0-9\-_]/', '-', $filename);

        return substr($filename, 0, 50);
    }
}
