export default {
  productList: [],
  tagList: [],
  selectedProduct: null,
  paginationModel: { pageSize: 20, page: 0 },
  totalCount: 0,
  filters: {
    search: "",
    category: "",
    tags: [],
    country: "",
    currency: "",
    sort_by: "created_at",
    sort_dir: "desc",
  },
  inputForm: {
    sp_name: "",
    sp_description: "",
    sp_sku: "",
    sp_mpc_id: "",
    sp_origin_country: "",
    sp_supplier_name: "",
    sp_supplier_contact: "",
    sp_base_price: "",
    sp_currency: "THB",
    sp_price_thb: "",
    sp_exchange_rate: "",
    sp_exchange_date: "",
    sp_unit: "ชิ้น",
    tag_ids: [],
    price_tiers: [],
    images: [],
  },
  mode: "",
};
